services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=delivery-nkt'
      - 'MYSQL_PASSWORD= '
      - 'MYSQL_ROOT_PASSWORD= '
      - 'MYSQL_USER= root'
    ports:
      - '3306'
